### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by unixorn** [mdarocha/zsh-windows-title#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license.

Please add a license - if you don't have one in mind,  I recommend [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

**Comment by mdarocha** [comment]
Ok, consider it done

**Comment by unixorn** [comment]
Added in https://github.com/unixorn/awesome-zsh-plugins/pull/755
